name: rentors
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_swiper: ^1.1.6

  intl: ^0.16.0
  html: ^0.14.0+2
  flutter_html: ^0.10.4
  flutter_svg: ^0.19.3

  url_launcher: ^5.4.1
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  equatable: ^1.1.0
  global_configuration: ^1.5.0
  circular_check_box: ^1.0.1
  dio: ^3.0.9
  flutter_bloc: ^4.0.0
  rflutter_alert: ^1.0.3

  pretty_dio_logger: ^1.1.1
  lottie: ^0.6.0
  timeago: ^2.0.26
  bottom_navigation_badge: ^1.0.3
  maps_launcher: ^1.2.0
  fluttertoast: ^4.0.0
  flutter_speed_dial: ^1.2.5
  extended_nested_scroll_view: ^1.0.1
  smooth_star_rating: 1.1.1
  country_code_picker: ^1.3.11
  carousel_slider: ^2.2.1
  flutter_secure_storage: ^4.2.0
  email_validator: ^1.0.0
  flutter_inappwebview: ^4.0.0+4
  rxdart: ^0.24.1
  image_picker: ^0.6.7+12
  date_format: ^1.0.9
  jiffy: ^3.0.1
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_messaging: ^8.0.0-dev.14
  optimized_cached_image: ^1.0.0
  stripe_payment: ^1.0.9
  flutterwave: 0.0.2
  razorpay_flutter: ^1.2.2
  credit_card_input_form: ^2.1.3
  flutter_local_notifications: ^3.0.2
  flurry_event: ^0.1.3
  shimmer: ^1.1.2
  animations: ^1.1.2
  
  google_mobile_ads: ^0.13.0
dependency_overrides:
  intl: ^0.17.0



dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.2.7
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/ic_launcher.png"

flutter_native_splash:
  color: "#FFFFFF"  # required parameter
  image: assets/img/splash/splash.png  # optional parameter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/cfg/configurations.json
    - assets/img/house.svg
    - assets/img/frame.svg
    - assets/img/facebook.svg
    - assets/img/heart.svg
    - assets/img/twitter.svg
    - assets/img/whatsapp.svg
    - assets/img/agreement.svg
    - assets/img/law.svg
    - assets/img/intro2.svg
    - assets/img/intro1.svg
    - assets/img/law.svg
    - assets/img/upload_second.svg
    - assets/img/upload.json
    - assets/img/flutterwave.png
    - assets/img/stripe.png
    - assets/img/razorpay.png
    - assets/img/ic_launcher_round.png
    - assets/img/splash/splash.png
    - assets/img/splash/logo.png
    - assets/img/splash/logo_light.png
    - assets/img/splash/intro_1_home.png
    - assets/img/splash/intro_1_home.webp
    - assets/img/splash/intro_2_home.webp
    - assets/img/splash/intro_3_home.webp
    - assets/img/splash/signin_background.jpeg
    - assets/img/splash/signin_background.png
    - assets/img/search.svg
    - assets/img/location.svg
    - assets/img/green-star.svg
    - assets/img/drawer/account.svg
    - assets/img/drawer/category.svg
    - assets/img/drawer/chat.svg
    - assets/img/drawer/help.svg
    - assets/img/drawer/history.svg
    - assets/img/drawer/home.svg
    - assets/img/drawer/house(1).svg
    - assets/img/drawer/house(2).svg
    - assets/img/drawer/house.svg
    - assets/img/drawer/logout.svg
    - assets/img/drawer/noti.svg
    - assets/img/drawer/post_request.svg
    - assets/img/drawer/rent_item.svg
    - assets/img/drawer/settings.svg
    - assets/img/drawer/settings2.svg
    - assets/img/drawer/wishlist.svg
    - assets/img/menu-bg.png
    - assets/network.json
    - assets/nodata.json
    - assets/loading.json
    


  fonts:
    - family: open
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 100
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800

    # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
